-- This file is automatically generated by mdtohs.hs,
-- and hence should not be changed manually.

-- The following code will appear in Lib.hs, which is
-- generated from this README.md file.

-- This file Lib.hs is imported in Formative2.hs .

{-# LANGUAGE Safe #-}

module Lib where

-- The following import is only used for marking.
import Data.Typeable (Typeable)


data Tree a = Empty
            | Branch [(Tree a, a)] (Tree a)
            deriving (Show, Typeable)

data Record k v = Pair { key :: k , value :: v }

instance Eq k => Eq (Record k v) where
  r == s = key r == key s

instance Ord k => Ord (Record k v) where
  r <= s = key r <= key s
