-- This file is automatically generated by mdtohs.hs,
-- and hence should not be changed manually.

-- The following code will appear in Lib.hs, which is
-- generated from this README.md file.

-- This file Lib.hs is imported in Formative2.hs .

{-# LANGUAGE Safe #-}

module Lib where

-- The following import is only used for marking.
import Data.Typeable (Typeable)
data Tree a = Empty
            | Branch [(Tree a, a)] (Tree a)
            deriving (Show, Typeable)

printTree :: Show a => Tree a -> IO ()
printTree n = putStrLn $ unlines $ printTree' n

printTree' :: Show a => Tree a -> [String]
printTree' Empty = ["Empty"]
printTree' (Branch ts u) =
        [ "Branch: t0" ++ pbounds ]
        ++
        map indent (concatMap printTree' children)
    where
        values   = map snd ts
        children = map fst ts ++ [u]

        pbounds = concatMap (\(b,i) -> " < " ++ show b ++ " < t" ++ show i)
                $ zip values [1..]

        indent :: String -> String
        indent s = "    " ++ s
